version: "3.8"

services:
   db:
       container_name: pg_container
       image: postgres:14
       restart: always
       environment:
           POSTGRES_USER: ${POSTGRES_USER}
           POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
           PGDATA: /var/lib/postgresql/data
       env_file: .env
       volumes:
           - db-data:/var/lib/postgresql/data
       ports:
           - 5432:5432
   pgadmin:
       container_name: pgadmin4_container
       image: dpage/pgadmin4:4.30
       restart: always
       environment:
           PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
           PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
           PGADMIN_LISTEN_PORT: 80
       env_file: .env
       ports:
           - 8080:80
       volumes:
           - pgadmin-data:/var/lib/pgadmin
volumes:
   db-data:
   pgadmin-data:
